### ISSUE TITLE
The file already exists

### ISSUE THREAD

**Issue by srjefers** [k-vernooy/dotfiles#1]
I tried to install by `./install.sh` but I'm getting always the same error. 

All the files can't be overwritted with this script :cry: , so I can't install your configs.

**Comment by k-vernooy** [comment]
As the script points out, you should always read the source for something like this before running it. The script just tries to symlink the right files into the right places. If these files already exist, it won't be able to link my files in. Just move your current files to a backup directory, then symlink my dots - there's really no need to use the install script.

This info is also restated with more detailed instructions at the bottom of the README.
